service: graphql-api

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:*"

functions:
  graphql:
    handler: src/handler.graphql
    events:
      - http:
          path: /graphql
          method: post
          cors: true
  graphiql:
    handler: src/handler.graphiql
    events:
      - http:
          path: /graphiql
          method: get

resources:
  Resources:
    ArtistsDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'artists'
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    SongsDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'songs'
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

custom:
  webpackIncludeModules: true
  serverless-offline:
    babelOptions:
      presets: ["env", "stage-0"]
  dynamodb:
    start:
      migrate: true
